config/routes.rb
Rails.application.routes.draw do
  namespace :cms do
    resources :slips
  end

  get 'slips/random', :to => 'slips#random_show'

  root :to => 'root#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cms.rb
module Cms
end

app/models/cms/slip.rb
class Cms::Slip < ApplicationRecord
  validates :content, :presence => true

  scope :sort_by_created_at_desc, -> { order(created_at: :desc) }
end

app/models/slip.rb
class Slip < ApplicationRecord
  scope :rand_slip, -> { find(self.pluck(:id).sample) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cms/slips_controller.rb
class Cms::SlipsController < CmsController
  before_action :set_cms_slip, only: [:show, :edit, :update, :destroy]

  # GET /cms/slips
  # GET /cms/slips.json
  def index
    @cms_slips = Cms::Slip.sort_by_created_at_desc
  end

  # GET /cms/slips/1
  # GET /cms/slips/1.json
  def show
  end

  # GET /cms/slips/new
  def new
    @cms_slip = Cms::Slip.new
  end

  # GET /cms/slips/1/edit
  def edit
  end

  # POST /cms/slips
  # POST /cms/slips.json
  def create
    @cms_slip = Cms::Slip.new(cms_slip_params)

    respond_to do |format|
      if @cms_slip.save
        format.html { redirect_to @cms_slip, notice: 'Slip was successfully created.' }
        format.json { render :show, status: :created, location: @cms_slip }
      else
        format.html { render :new }
        format.json { render json: @cms_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cms/slips/1
  # PATCH/PUT /cms/slips/1.json
  def update
    respond_to do |format|
      if @cms_slip.update(cms_slip_params)
        format.html { redirect_to @cms_slip, notice: 'Slip was successfully updated.' }
        format.json { render :show, status: :ok, location: @cms_slip }
      else
        format.html { render :edit }
        format.json { render json: @cms_slip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cms/slips/1
  # DELETE /cms/slips/1.json
  def destroy
    @cms_slip.destroy
    respond_to do |format|
      format.html { redirect_to cms_slips_url, notice: 'Slip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cms_slip
      @cms_slip = Cms::Slip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cms_slip_params
      params.require(:cms_slip).permit(:content)
    end
end

app/controllers/cms_controller.rb
class CmsController < ActionController::Base
  layout "cms"
  protect_from_forgery with: :exception
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  def index
  end
end

app/controllers/slips_controller.rb
class SlipsController < ApplicationController

  # GET /slips/random
  def random_show
    slip = Slip.rand_slip
    render json: {content: slip.content}
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for_flash(flash_type)
    case flash_type
    when 'success'
      'alert-success'
    when 'error'
      'alert-danger'
    when 'alert'
      'alert-warning'
    when 'notice'
      'alert-info'
    else
      flash_type.to_s
    end
  end
end

app/views/cms/slips/_form.html.erb
<%= form_with(model: cms_slip, local: true) do |form| %>
  <% if cms_slip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cms_slip.errors.count, "error") %> prohibited this slip from being saved:</h2>

      <ul>
      <% cms_slip.errors.full_messages.each do |message| %>
        <li class="text-danger"><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="form-group">
      <label for="cms_slip_content">Content of this Slip</label>
      <%= form.text_area :content, id: :cms_slip_content, class: 'form-control', rows: 3 %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit (action_name == "new") ? 'Create' : 'Update', class: 'btn btn-primary' %>
    <%= link_to 'Back to the list', cms_slips_path, class: 'btn btn-default' %>
  </div>
<% end %>

app/views/cms/slips/edit.html.erb
<h1>Editing Slip (#<%= @cms_slip.id %>)</h1>

<%= render 'form', cms_slip: @cms_slip %>

app/views/cms/slips/index.html.erb
<h1>Fortune Slips</h1>

<hr>
<a href="<%= new_cms_slip_path %>" class="btn btn-primary mb-5">Create A Slip</a>

<table class="table">
  <thead>
    <tr>
      <th>#Id</th>
      <th>Content</th>
      <th>Created At</th>
      <th>Updated At</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @cms_slips.each do |cms_slip| %>
      <tr>
        <td><%= cms_slip.id %></td>
        <td><%= truncate cms_slip.content, length: 15 %></td>
        <td><%= cms_slip.created_at %></td>
        <td><%= cms_slip.updated_at %></td>
        <td><%= link_to 'Edit', edit_cms_slip_path(cms_slip) %> | <%= link_to 'Destroy', cms_slip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/cms/slips/new.html.erb
<h1>Create A Slip</h1>
<hr>

<%= render 'form', cms_slip: @cms_slip %>

app/views/cms/slips/show.html.erb
<h1>Detail of Slip #<%= @cms_slip.id %></h1>
<hr>

<table class="table table-striped">
  <tbody>
    <tr>
      <th width="10%"><strong>#ID:</strong></th>
      <td><%= @cms_slip.id %></td>
    </tr>
    <tr>
      <th><strong>Content:</strong></th>
      <td><%= @cms_slip.content %></td>
    </tr>
    <tr>
      <th><strong>Created At:</strong></th>
      <td><%= @cms_slip.created_at %></td>
    </tr>
    <tr>
      <th><strong>Updated At:</strong></th>
      <td><%= @cms_slip.updated_at %></td>
    </tr>
  </tbody>
</table>

<%= link_to 'Edit', edit_cms_slip_path(@cms_slip), class: "btn btn-primary mr-2" %>
<%= link_to 'Back to the list', cms_slips_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookieToday</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <!-- Javascript -->
    <%= yield :javascript %>
  </body>
</html>

app/views/layouts/cms.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CookieToday</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'cms', media: 'all' %>
    <%= javascript_include_tag 'cms' %>
  </head>

  <body>

    <div class="container">
      <% flash.each do |type, msg| %>
        <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show">
          <%= msg %>
          <button class="close" data-dismiss="alert">x</button>
        </div>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/root/index.html.erb
<h1>Cookie Today!</h1>
<div id="slip_content" class="mb-3 mt3" style="display: none; border: solid 1px #ccc; padding: 20px;"></div>
<button id="btn_open_cookie" class="btn btn-primary mb-5">打開一個餅乾</button>


<% content_for :javascript do %>
  <script type="text/javascript" charset="utf-8">
      $(function(){
          Root.init();
      });
  </script>
<% end %>